name: YouTube Auto Monitor

on:
  schedule:
    # Check for new videos every 2 hours
    - cron: '0 */2 * * *'
    # Process pending videos every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-new-videos:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 */2 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check for new videos
        run: |
          curl -X POST https://oonugywfdtzrcrydmazk.supabase.co/functions/v1/check-new-videos \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbnVneXdmZHR6cmNyeWRtYXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Nzc5MzgsImV4cCI6MjA3NjQ1MzkzOH0.bdZnEMe1TTF7eqjedzXkuC0geqK8DGRY5MOyjR3E9XQ"

  process-pending:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/5 * * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Process pending videos
        run: |
          curl -X POST https://oonugywfdtzrcrydmazk.supabase.co/functions/v1/process-pending-videos \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbnVneXdmZHR6cmNyeWRtYXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Nzc5MzgsImV4cCI6MjA3NjQ1MzkzOH0.bdZnEMe1TTF7eqjedzXkuC0geqK8DGRY5MOyjR3E9XQ"
